import { AST, ASTParser } from "./astparser.js";
const parser = new ASTParser;
export type TypeRule = { prefix: string, inferMode: string, ast: AST, id: string, postfix: string };
export function initTypeSystem() {
    let typeName: string;
    // let localId: { [key: string]: number } = {};
    const ruleList: TypeRule[] = [];
    function addRule(postfix: string, astStr: string) {
        const ast = parser.parse(astStr);
        let inferMode = "";
        if (postfix[0] === "@" || postfix[0] === "_") {
            inferMode = postfix[0];
            postfix = postfix.slice(1);
        }
        // localId[typeName] ??= 0;
        // const id = typeName + (localId[typeName]++);
        ruleList.push({ prefix: typeName.replace(/\..+$/, ""), ast, id: typeName, postfix, inferMode });
    }

    // typeName = "Function";
    // addRule("类型", "Px:?A,?b x:U_");
    // addRule("定义", "?A->?B === Px:?A,?B");
    // addRule("构造", "Lx:?A.?f x : Px:?A.?b x");
    // addRule("解构", "(Lx:?A.?f x) ?a : ?b ?a");
    // addRule("_计算", "(Lx:?A.?f x) ?a === ?f ?a");
    // addRule("_计算", "(Lx:?A.?f x) === ?f");
    typeName = "True";
    addRule("类型", "True:U");
    addRule("构造", "true:True");
    typeName = "True.ind";
    addRule("@解构", "@ind_True : Pu:U@,PC:True->Uu,Pc:C true,Px:True,C x");
    addRule("@解构", "ind_True := @ind_True _");
    addRule("_解构", "ind_True");
    addRule("计算", "ind_True ?C ?ctrue true === ?ctrue");

    typeName = "False";
    addRule("类型", "False:U");
    typeName = "False.ind";
    addRule("@解构", "@ind_False : Pu:U@,PC:False->Uu,Px:False,C x");
    addRule("@解构", "ind_False := @ind_False _");
    addRule("_解构", "ind_False");

    typeName = "False.not";
    addRule("定义", "not:=La:U_.a->False");

    typeName = "Bool";
    addRule("类型", "Bool:U");
    addRule("构造", "0b:Bool");
    addRule("构造", "1b:Bool");
    typeName = "Bool.ind";
    addRule("@解构", "@ind_Bool : Pu:U@,PC:Bool->Uu,Pc0b:C 0b,Pc1b:C 1b,Px:Bool,C x");
    addRule("@解构", "ind_Bool := @ind_Bool _");
    addRule("_解构", "ind_Bool");
    addRule("计算", "ind_Bool ?C ?c0b ?c1b 0b === ?c0b");
    addRule("计算", "ind_Bool ?C ?c0b ?c1b 1b === ?c1b");

    typeName = "nat";
    addRule("类型", "nat:U");
    addRule("构造", "0:nat");
    addRule("构造", "succ:nat->nat");
    typeName = "nat.ind";
    addRule("@解构", "@ind_nat : Pu:U@,PC:nat->Uu,Pc0:C 0,Pcs:(Px:nat,Py:C x,C (succ x)),Px:nat,C x");
    addRule("@解构", "ind_nat := @ind_nat _");
    addRule("_解构", "ind_nat");
    addRule("计算", "ind_nat ?C ?c0 ?csucc 0 === ?c0");
    addRule("计算", "ind_nat ?C ?c0 ?csucc (succ ?n) === ?csucc ?n (ind_nat ?C ?c0 ?csucc ?n)");
    typeName = "nat.pred";
    addRule("定义", "pred:=ind_nat (Lx:nat.nat) 0 (Lx:nat.Ly:nat.x)");
    typeName = "nat.double";
    addRule("定义", "double:=ind_nat (Lx:nat.nat) 0 (Ly:nat.Lz:nat.succ (succ z))");
    addRule("@计算", "double 0 === 0");
    addRule("@计算", "double (succ ?n) === succ (succ (double ?n))");
    typeName = "nat.add";
    addRule("定义", "add:=Lx:nat.ind_nat (Ly:nat.nat) x (Lx:nat.succ)");
    typeName = "nat.mul";
    addRule("定义", "mul:=Lx:nat.ind_nat (Ly:nat.nat) 0 (Lk:nat.Ln:nat.add n x)");
    typeName = "nat.pow";
    addRule("定义", "pow:=Lx:nat.ind_nat (Ly:nat.nat) 1 (Lk:nat.Ln:nat.mul n x)");
    typeName = "nat.!";
    addRule("定义", "factorial:=ind_nat (Ly:nat.nat) 1 (Lk:nat.Ln:nat.mul n (succ k))");
    // typeName = "nat.code";
    // addRule("定义", "code_nat:=ind_nat (Lx:nat.nat->U) (ind_nat (Ly:nat.U) True (Ly:nat.Lz:U.False)) (Lx:nat.Lf:nat->U.ind_nat (Ly:nat.U) False (Ly:nat.Lz:U.f y))");
    // addRule("@计算", "code_nat 0 0 === True");
    // addRule("@计算", "code_nat 0 (succ ?x) === False");
    // addRule("@计算", "code_nat (succ ?x) 0 === False");
    // addRule("@计算", "code_nat (succ ?x) (succ ?y) === code_nat ?x ?y");


    typeName = "eq";
    addRule("@类型", "@eq : Pu:U@,Pa:Uu,a->a->Uu");
    addRule("@类型", "eq := @eq _ _");
    addRule("_类型", "eq");
    typeName = "eq.=";
    addRule("定义", "?1 = ?2 === eq ?1 ?2");
    typeName = "eq";
    addRule("@构造", "@refl : Pu:U@,Pa:Uu,Px:a,@eq u a x x");
    addRule("@构造", "refl := @refl _ _");
    addRule("_构造", "refl");
    typeName = "eq.rfl";
    addRule("@构造", "rfl := refl _");
    addRule("_构造", "rfl");
    typeName = "eq.ind";
    addRule("@解构", "@ind_eq : Pu:U@,Pv:U@,Pa:Uu,Px:a,PC:Py:a,(@eq u a x y)->Uv,Pc:C x (@refl u a x),Py:a,Pm:@eq u a x y,C y m");
    addRule("@解构", "ind_eq := @ind_eq _ _ _");
    addRule("_解构", "ind_eq");
    addRule("计算", "ind_eq ?x ?C ?crfl ?x (refl ?x) === ?crfl");
    addRule("@计算", "ind_eq _ _ ?crfl _ (refl ?x) === ?crfl");
    addRule("@计算", "ind_eq _ _ ?crfl _ (@refl ?1 ?2 ?3) === ?crfl");
    addRule("@计算", "ind_eq _ _ ?crfl _ rfl === ?crfl");
    // addRule("@计算", "@ind_eq _ _ _ _ _ ?crfl _ (@refl ?1 ?2 ?3) === ?crfl");
    // addRule("@计算", "@ind_eq _ _ _ _ _ ?crfl _ (refl ?x) === ?crfl");
    // addRule("@计算", "@ind_eq _ _ _ _ _ ?crfl _ rfl === ?crfl");
    typeName = "eq.ind2";
    addRule("@解构", "@ind_eq2 : Pu:U@,Pv:U@,Pa:Uu,PC:Px:a,Py:a,(@eq u a x y)->Uv,Pc:Px:a,C x x (@refl u a x),Px:a,Py:a,Pm:@eq u a x y,C x y m");
    addRule("@解构", "ind_eq2 := @ind_eq2 _ _ _");
    addRule("_解构", "ind_eq2");
    addRule("计算", "ind_eq2 ?C ?crfl ?x ?x (refl ?x) === ?crfl ?x");
    addRule("@计算", "ind_eq2 ?C ?crfl _ _ (@refl ?1 ?2 ?x) === ?crfl ?x");
    addRule("@计算", "ind_eq2 ?C ?crfl ?x _ rfl === ?crfl ?x");
    // addRule("@计算", "@ind_eq2 _ _ _ ?C ?crfl ?x ?x (@refl _ _ ?x) === ?crfl ?x");
    // addRule("@计算", "@ind_eq2 _ _ _ ?C ?crfl ?x ?x (refl ?x) === ?crfl ?x");
    // addRule("@计算", "@ind_eq2 _ _ _ ?C ?crfl ?x ?x (rfl) === ?crfl ?x");
    typeName = "eq.ap";
    addRule("@定义", "@ap:Pa:U_.Pb:U_.Px:a.Py:a.Pf:a->b.x=y->f x=f y");
    // addRule("@定义", "@ap:=La:U_.Lb:U_.Lx:a.Ly:a.Lf:a->b.Lp:eq x y.ind_eq x (Ly:a.Lm:eq x y.eq (f x) (f y)) rfl y p");
    addRule("@定义", "ap:=@ap _ _ _ _");
    addRule("定义", "ap");
    addRule("计算", "ap ?f (refl ?x) === refl (?f ?x)");
    addRule("@计算", "ap ?f (@refl ?1 ?2 ?x) === refl (?f ?x)");
    addRule("@计算", "ap ?f rfl === rfl");
    typeName = "eq.apid";
    addRule("@定义", "@apid:Pa:U_,Px:a.Py:a.Pp:x=y,ap (Lx:a.x) p = p");
    addRule("@定义", "apid:=@apid _ _ _");
    addRule("定义", "apid");
    addRule("计算", "apid (refl ?x) === refl (refl ?x)");
    addRule("@计算", "apid (@refl ?1 ?2 ?x) === refl (refl ?x)");
    addRule("@计算", "apid rfl === refl rfl");
    typeName = "eq.apconst";
    addRule("@定义", "@apconst:Pa:U_,Pb:U_.Px:a.Py:a.Pp:x=y,Pk:b.ap (Lx:a.k) p = (refl k)");
    addRule("@定义", "apconst:=@apconst _ _ _ _");
    addRule("定义", "apconst");
    addRule("计算", "apconst (refl ?x) ?k === refl (refl ?k)");
    addRule("@计算", "apconst (@refl ?1 ?2 ?x) ?k === refl (refl ?k)");
    addRule("@计算", "apconst rfl ?k === refl (refl ?k)");
    typeName = "eq.trans";
    // addRule("@定义", "@trans:=La:U_.Lx:a.Ly:a.Lb:a->U_.ind_eq x (Ly:a.Lm:eq x y.(b x)->(b y)) (Lx:b x.x) y");
    addRule("@定义", "@trans:Pu:U@,Pv:U@,Pa:Uu.Px:a.Py:a.Pb:a->Uv.x=y->b x->b y");
    addRule("@定义", "trans:=@trans _ _ _ _ _");
    addRule("_定义", "trans");
    addRule("计算", "trans ?C (refl ?x) ?y === ?y");
    addRule("@计算", "trans ?C (@refl ?1 ?2 ?x) ?y === ?y");
    addRule("@计算", "trans ?C rfl ?y=== ?y");
    typeName = "eq.apd";
    addRule("@定义", "@apd:Pu:U@,Pv:U@,Pa:Uu.Px:a.Py:a.Pb:a->Uv.Pf:Px:a,b x.Pp:x=y.trans b p (f x) = f y");
    // addRule("@定义", "@apd:=La:U_.Lx:a.Ly:a.Lb:a->U_.Lf:Px:a,b x.Lp:eq x y.ind_eq x (Ly:a.Lp:eq x y. eq (trans b p (f x)) (f y)) (refl (f x)) y p");
    addRule("@定义", "apd:=@apd _ _ _ _ _ _");
    addRule("_定义", "apd");
    addRule("计算", "apd ?f (refl ?x) === refl (?f ?x)");
    addRule("@计算", "apd ?f rfl === rfl");
    addRule("@计算", "apd ?f (@refl ?1 ?2 ?x) === refl (?f ?x)");
    typeName = "eq.inv";
    addRule("@定义", "@inveq:Pu:U@.Pa:Uu.Px:a.Py:a.x=y->y=x");
    // addRule("@定义", "@inveq:=La:U_.Lx:a.ind_eq x (Ly:a.Lm:eq x y.eq y x) rfl");
    addRule("@定义", "inveq:=@inveq _ _ _ _");
    addRule("_定义", "inveq");
    addRule("计算", "inveq (refl ?x) === refl ?x");
    addRule("@计算", "inveq rfl === rfl");
    addRule("@计算", "inveq (@refl ?1 ?2 ?x) === @refl ?1 ?2 ?x");
    typeName = "eq.*";
    addRule("@定义", "@compeq:Pu:U@.Pa:Uu.Px:a.Py:a.Pz:a.x=y->y=z->x=z");
    // addRule("@定义", "@compeq:=La:U_.Lx:a.Ly:a.Lz:a.ind_eq x (Ly:a.Lm:eq x y.(eq y z)->(eq x z)) (Lm:eq x z.m) y");
    addRule("@定义", "compeq:=@compeq _ _ _ _ _");
    addRule("_定义", "compeq");
    addRule("_定义", "?1 * ?2 === compeq ?1 ?2");
    addRule("计算", "(refl ?x) * ?p === ?p ");
    addRule("@计算", "compeq rfl ?p === ?p ");
    addRule("@计算", "compeq (refl ?x) ?p === ?p ");
    addRule("@计算", "compeq (@refl ?1 ?2 ?x) ?p === ?p ");

    typeName = "eq.rightrfl";
    addRule("@定义", "@rightrfl:Pa:U_.Px:a.Py:a.Pm:x=y.m*rfl=m")
    // addRule("@定义", "@rightrfl:=La:U_.Lx:a.ind_eq x (Ly:a.Lm:x=y.m*rfl=m) rfl")
    addRule("@定义", "rightrfl:=@rightrfl _ _ _");
    addRule("定义", "rightrfl");
    addRule("计算", "rightrfl (refl ?x) === refl (refl ?x)");
    addRule("@计算", "rightrfl rfl === refl rfl");
    addRule("@计算", "rightrfl (@refl ?1 ?2 ?x) === refl (refl ?x)");
    typeName = "eq.invinv";
    addRule("@定义", "@invinveq:Pa:U_.Px:a.Py:a.Pm:x=y.inveq(inveq m)=m")
    // addRule("@定义", "@invinveq:=La:U_.Lx:a.ind_eq x (Ly:a.Lm:x=y.inveq(inveq m)=m) rfl")
    addRule("@定义", "invinveq:=@invinveq _ _ _");
    addRule("定义", "invinveq");
    addRule("计算", "invinveq (refl ?x) === refl (refl ?x)");
    addRule("@计算", "invinveq (@refl ?1 ?2 ?x) === refl (refl ?x)");
    addRule("@计算", "invinveq rfl === refl rfl");
    typeName = "eq.rightinv";
    addRule("@定义", "@rightinveq:Pa:U_.Px:a.Py:a.Pm:x=y.m*(inveq m)=rfl")
    // addRule("@定义", "@rightinveq:=La:U_.Lx:a.ind_eq x (Ly:a.Lm:x=y.m*(inveq m)=rfl) rfl")
    addRule("@定义", "rightinveq:=@rightinveq _ _ _");
    addRule("定义", "rightinveq");
    addRule("计算", "rightinveq (refl ?x) === refl (refl ?x)");
    addRule("@计算", "rightinveq (@refl ?1 ?2 ?x) === refl (refl ?x)");
    addRule("@计算", "rightinveq rfl === refl rfl");
    typeName = "eq.leftinv";
    addRule("@定义", "@leftinveq:Pa:U_.Px:a.Py:a.Pm:x=y.(inveq m)*m=rfl")
    // addRule("@定义", "@leftinveq:=La:U_.Lx:a.ind_eq x (Ly:a.Lm:x=y.(inveq m)*m=rfl) rfl")
    addRule("@定义", "leftinveq:=@leftinveq _ _ _");
    addRule("定义", "leftinveq");
    addRule("计算", "leftinveq (refl ?x) === refl (refl ?x)");
    addRule("@计算", "leftinveq (@refl ?1 ?2 ?x) === refl (refl ?x)");
    addRule("@计算", "leftinveq rfl === refl rfl");
    typeName = "eq.*inv";
    addRule("@定义", "@compinveq:Pa:U_.Px:a,Py:a,Pz:a,Pm:x=y,Pn:y=z,inveq (m*n) = (inveq n)*(inveq m)")
    addRule("@定义", "compinveq:=@compinveq _ _ _ _");
    addRule("定义", "compinveq");
    addRule("计算", "compinveq (refl ?x) ?y === inveq (rightrfl (inveq ?y))");
    addRule("@计算", "compinveq (@refl ?1 ?2 ?x) ?y === inveq (rightrfl (inveq ?y))");
    addRule("@计算", "compinveq rfl ?y === inveq (rightrfl (inveq ?y))");

    typeName = "eq.*assoc";
    addRule("@定义", "@compeqassoc:Pa:U_.Px:a.Py:a.Pz:a.Pw:a.Pm:x=y.Pn:y=z.Po:z=w.(m▪n)▪o=m▪(n▪o)")
    // addRule("@定义", "@compeqassoc:=λa:U_.λx:a.λz:a.λw:a.ind_eq x (λy':a.λm:x=y'.Πn:y'=z,Πo:z=w,(m▪n)▪o=m▪(n▪o)) (λn:x=z.λo:z=w.rfl)")
    addRule("@定义", "compeqassoc:=@compeqassoc _ _ _ _ _")
    addRule("_定义", "compeqassoc");
    addRule("计算", "compeqassoc (refl ?x) ?a ?b === refl (?a*?b)");
    addRule("@计算", "compeqassoc rfl ?a ?b === refl (?a*?b)");
    addRule("@计算", "compeqassoc (@refl ?1 ?2 ?x) ?a ?b === refl (?a*?b)");
    typeName = "eq.transconst";
    addRule("@定义", "@transconst:Pa:U_.Pb:U_.Px:a.Py:a.Pm:eq x y.Pk:b.trans (λx:a.b) m k = k");
    // addRule("@定义", "@transconst:=λa:U_.λb:U_.λx:a.λy:a.λm:eq x y.λk:b.ind_eq x (λy':a.(λm:eq x y'.eq (trans (λx:a.b) m k) k)) rfl y m");
    addRule("@定义", "transconst:=@transconst _ _ _ _");
    addRule("_定义", "transconst");
    addRule("计算", "transconst (refl ?x) ?y === refl ?y");
    addRule("@计算", "transconst rfl ?y === refl ?y");
    addRule("@计算", "transconst (@refl ?1 ?2 ?x) ?y === refl ?y");
    typeName = "eq.transright";
    addRule("@定义", "@transright:Pa:U_,Px0:a,Px1:a,Px2:a,Pp:x1=x2,Pq:x0=x1,trans (Lx:a,x0=x) p q = q*p");
    addRule("@定义", "transright:= @transright _ _ _ _");
    addRule("_定义", "transright");
    addRule("计算", "transright (refl ?x) ?q === inveq (rightrfl ?q)");
    addRule("@计算", "transright rfl ?q === inveq (rightrfl ?q)");
    addRule("@计算", "transright (@refl ?1 ?2 ?x) ?q === inveq (rightrfl ?q)");
    typeName = "eq.transleft";
    addRule("@定义", "@transleft:Pa:U_,Px0:a,Px1:a,Px2:a,Pp:x1=x2,Pq:x1=x0,trans (Lx:a,x=x0) p q = (inveq p)*q");
    addRule("@定义", "transleft:= @transleft _ _ _ _");
    addRule("_定义", "transleft");
    addRule("计算", "transleft (refl ?x) ?q === refl ?q");
    addRule("@计算", "transleft rfl ?q === refl ?q");
    addRule("@计算", "transleft (@refl ?1 ?2 ?x) ?q === refl ?q");
    typeName = "eq.transleftright";
    addRule("@定义", "@transleftright:Pa:U,Px0:a,Px1:a,Px2:a,Pp:x1=x2,Pq:x1=x1,trans (Lx:a,x=x) p q = (inveq p)*q*p");
    addRule("@定义", "transleftright:= @transleftright _ _ _ _");
    addRule("_定义", "transleftright");
    addRule("计算", "transleftright (refl ?x) ?q === inveq (rightrfl ?q)");
    addRule("@计算", "transleftright rfl ?q === inveq (rightrfl ?q)");
    addRule("@计算", "transleftright (@refl ?1 ?2 ?x) ?q === inveq (rightrfl ?q)");

    typeName = "eq.transeq";
    addRule("@定义", "@transeq:Pa:U_.Pb:U_.Px:a.Py:a.Pf:a->b.Pg:a->b.Pp:x=y.Pq:f x=g x.trans (Lx:a.f x=g x) p q = inveq (ap f p) * q * (ap g p)");
    // addRule("@定义", "@transconst:=λa:U_.λb:U_.λx:a.λy:a.λm:eq x y.λk:b.ind_eq x (λy':a.(λm:eq x y'.eq (trans (λx:a.b) m k) k)) rfl y m");
    addRule("@定义", "transeq:=@transeq _ _ _ _");
    addRule("_定义", "transeq");
    addRule("计算", "transeq ?f ?g (refl ?x) ?q === inveq (rightrfl ?q)");
    addRule("@计算", "transeq _ _ rfl ?q === inveq (rightrfl ?q)");
    addRule("@计算", "transeq _ _ (@refl ?1 ?2 ?x) ?q === inveq (rightrfl ?q)");
    // typeName = "eq.apd_ap";
    // addRule("@定义", "@apd_ap:Pa:U_.Pb:U_.Px:a.Py:a.Pf:a->b.Pp:x=y.apd f p = (transconst p (f x)) * (ap f p)");
    // // addRule("@定义", "@apd_ap:=λa:U_.λb:U_.λx:a.λy:a.λf:a→b.λp:eq x y.ind_eq x (λy':a.(λp:eq x y'.eq (apd (λx:a.b) f p) (compeq (transconst p (f x)) (ap f p)))) rfl y p");
    // addRule("@定义", "apd_ap:=@apd_ap _ _ _ _");
    // addRule("_定义", "apd_ap");
    // addRule("计算", "(apd_ap ?f (refl ?x))===(refl (refl (?f ?x)))");
    // addRule("@计算", "apd_ap ?f rfl === refl rfl");
    // addRule("@计算", "(apd_ap ?f (@refl ?1 ?2 ?x))===(refl (refl (?f ?x)))");

    // addRule("@定义", "@ap_apd:=(λa:U_.(λb:U_.(λx:a.(λy:a.(λf:(a→b).(λp:eq x y.ind_eq x (λy':a.(λp:eq x y'.eq (compeq (inveq (transconst p (f x))) (apd (λx:a.b) f p)) (ap f p))) rfl y p))))))");
    // addRule("@定义", "ap_apd:=@ap_apd _ _ _ _");
    // addRule("计算", "(ap_apd ?f (refl ?x))===(refl (refl (?f ?x)))");
    // addRule("@计算", "ap_apd ?f rfl === refl rfl");

    typeName = "Prod";
    // addRule("@类型", "@Prod : Pu:U@,Pv:U@,Pa:Uu,Pb:a->Uv,(U(@max u v))");
    addRule("_类型", "Sx:?A,?B x : U_");
    addRule("_类型", "?A X ?B === Sx:?A,?B");
    addRule("@构造", "@pair : Pu:U@,Pv:U@,Pa:Uu,Pb:a->Uv,Pxa:a,Pxb:b xa,Sx:a,b x");
    addRule("@构造", "pair := @pair _ _ _");
    addRule("_构造", "pair");
    addRule("构造", "(?a,?b) === pair (Lx:?A,?B) ?a ?b");
    typeName = "Prod.ind";
    addRule("@解构", "@ind_Prod : Pu:U@,Pv:U@,Pw:U@,Pa:Uu,Pb:a->Uv,PC:(Sx:a,b x)->Uw,(Px0:a,Px1:b x0,(C (@pair u v a b x0 x1)))->(Px:Sx:a,b x,C x)");
    addRule("@解构", "ind_Prod := @ind_Prod _ _ _ _");
    addRule("_解构", "ind_Prod");
    addRule("计算", "ind_Prod ?b ?C ?c (pair ?b ?xa ?xb) === ?c ?xa ?xb");
    addRule("@计算", "ind_Prod _ _ ?c (@pair ?1 ?2 ?3 ?4 ?xa ?xb) === ?c ?xa ?xb");
    typeName = "Prod.pr0";
    addRule("@定义", "@pr0:Pa:U_.Pb:a->U_.Px:Sz:a,b z.a");
    // addRule("@定义", "@pr0:=La:U_.Lb:a->U_.ind_Prod (Lx:a.b x) (Lx:Sz:a,b z.a) (Lx:a.Ly:b x.x)");
    addRule("@定义", "pr0:=@pr0 _ _");
    addRule("_定义", "pr0");
    addRule("计算", "pr0 (pair ?f ?a ?b) === ?a");
    addRule("@计算", "pr0 (@pair ?1 ?2 ?3 ?f ?a ?b) === ?a");
    typeName = "Prod.pr1";
    addRule("@定义", "@pr1:Pa:U_.Pb:U_.(aXb)->b");
    // addRule("@定义", "@pr1:=La:U_.Lb:U_.ind_Prod (Lx:a.b) (Lm:aXb.b) (Lxa:a.Lxb:b.xb)");
    addRule("@定义", "pr1:=@pr1 _ _");
    addRule("_定义", "pr1");
    addRule("_计算", "pr1 (?a, ?b) === ?b");
    addRule("@计算", "pr1 (pair ?f ?a ?b) === ?b");
    addRule("@计算", "pr1 (@pair ?1 ?2 ?3 ?f ?a ?b) === ?b");
    typeName = "Prod.prd1";
    addRule("@定义", "@prd1:Pa:U_.Pb:a->U_.Pm:Sz:a,b z.b (pr0 m)");
    // addRule("@定义", "@prd1:=La:U_.Lb:a->U_.ind_Prod b (Lm:Sz:a,b z.b (pr0 m)) (Lxa:a.Lxb:b xa.xb)");
    addRule("@定义", "prd1:=@prd1 _ _");
    addRule("_定义", "prd1");
    addRule("计算", "prd1 (pair ?f ?a ?b) === ?b");
    addRule("@计算", "prd1 (@pair ?1 ?2 ?3 ?f ?a ?b) === ?b");

    typeName = "Sum";
    addRule("@类型", "@Sum : Pu:U@,Pv:U@,Uu->Uv->(U(@max u v))");
    addRule("@类型", "?A + ?B := @Sum _ _ ?A ?B");
    addRule("_类型", "?A + ?B : U(@max ?u ?v)");
    addRule("@构造", "@inl : Pu:U@,Pv:U@,Pa:Uu,Pb:Uv,Pxa:a,a + b");
    addRule("@构造", "inl := @inl _ _ _ _");
    addRule("_构造", "inl");
    addRule("@构造", "@inr : Pu:U@,Pv:U@,Pa:Uu,Pb:Uv,Pxb:b,a + b");
    addRule("@构造", "inr := @inr _ _ _ _");
    addRule("_构造", "inr");
    typeName = "Sum.ind";
    addRule("@解构", "@ind_Sum : Pu:U@,Pv:U@,Pw:U@,Pa:Uu,Pb:Uv,PC:(a + b)->Uw,(Pxl:a,(C (inl xl)))->(Pxr:b,(C (inr xr)))->(Px:a + b,C x)");
    addRule("@解构", "ind_Sum := @ind_Sum _ _ _ _ _");
    addRule("_解构", "ind_Sum");
    addRule("计算", "ind_Sum ?C ?cinl ?cinr (inl ?xa) === ?cinl ?xa");
    addRule("计算", "ind_Sum ?C ?cinl ?cinr (inr ?xb) === ?cinr ?xb");
    addRule("@计算", "ind_Sum _ ?cinl _ (@inl ?1 ?2 ?3 ?4 ?xa) === ?cinl ?xa");
    addRule("@计算", "ind_Sum _ _ ?cinr (@inr ?1 ?2 ?3 ?4 ?xb) === ?cinr ?xb");
    typeName = "Z";
    addRule("类型", "Z:U");
    addRule("构造", "0Z:Z");
    addRule("构造", "pos:nat->Z");
    addRule("构造", "neg:nat->Z");
    addRule("@解构", "@ind_Z:Pu:U@,PC:Z->Uu,Pc0:C 0Z,Pcp:Px:nat,C (pos x),Pcn:Px:nat,C (neg x),Px:Z,C x");
    addRule("@解构", "ind_Z:=@ind_Z _");
    addRule("_解构", "ind_Z");
    addRule("计算", "ind_Z ?C ?c0 ?cp ?cn 0Z === ?c0");
    addRule("计算", "ind_Z ?C ?c0 ?cp ?cn (pos ?n) === ?cp ?n");
    addRule("计算", "ind_Z ?C ?c0 ?cp ?cn (neg ?n) === ?cn ?n");

    typeName = "Z.nat2";
    addRule("定义", "nat2Z:=ind_nat (λh:nat.Z) 0Z (λh:nat.λ_:Z.pos h)");
    addRule("@计算", "nat2Z 0 === 0Z");
    addRule("@计算", "nat2Z (succ ?x) === pos ?x");
    typeName = "Z.abs";
    addRule("定义", "absZ:=ind_Z (Lx:Z,Z) 0Z pos pos");
    addRule("@计算", "absZ 0Z === 0");
    addRule("@计算", "absZ (pos ?x) === pos ?x");
    addRule("@计算", "absZ (neg ?x) === pos ?x");
    typeName = "Z.succ";
    addRule("定义", "succZ:=ind_Z (λh:Z.Z) (pos 0) (λh:nat.pos (succ h)) (ind_nat (λh:nat.Z) 0Z (λh:nat.λ_:Z.neg h))");
    addRule("@计算", "succZ 0Z === pos 0");
    addRule("@计算", "succZ (pos ?x) === pos (succ ?x)");
    addRule("@计算", "succZ (neg 0) === 0Z");
    addRule("@计算", "succZ (neg (succ ?x)) === neg ?x");
    typeName = "Z.pred";
    addRule("定义", "predZ:=ind_Z (λh:Z.Z) (neg 0) (ind_nat (λh:nat.Z) 0Z (λh:nat.λ_:Z.pos h)) (λh:nat.neg (succ h))");
    addRule("@计算", "predZ 0Z === neg 0");
    addRule("@计算", "predZ (pos 0) === 0Z");
    addRule("@计算", "predZ (pos (succ ?x)) === pos ?x");
    addRule("@计算", "predZ (neg ?x) === neg (succ ?x)");
    typeName = "Z.predsucc";
    addRule("定义", "pred_succZ:=ind_Z (λx:Z.predZ (succZ x)=x) rfl (λx:nat.rfl) (ind_nat (λx:nat.predZ (succZ (neg x))=neg x) rfl (λx:nat.λy:predZ (succZ (neg x))=neg x.rfl))");
    typeName = "Z.succpred";
    addRule("定义", "succ_predZ:=ind_Z (λx:Z.succZ (predZ x)=x) rfl (ind_nat (λx:nat.succZ (predZ (pos x))=pos x) rfl (λx:nat.λy:succZ (predZ (pos x))=pos x.rfl)) (λx:nat.rfl)");
    typeName = "Z.neg";
    addRule("定义", "negZ:=ind_Z (λh:Z.Z) 0Z neg pos");
    addRule("@计算", "negZ 0Z === 0Z");
    addRule("@计算", "negZ (pos ?x) === neg ?x");
    addRule("@计算", "negZ (neg ?x) === pos ?x");
    typeName = "Z.add";
    addRule("定义", "addZ:=λx:Z.ind_Z (λy:Z.Z) x (ind_nat (λy:nat.Z) (succZ x) (λy:nat.succZ)) (ind_nat (λy:nat.Z) (predZ x) (λy:nat.predZ))");
    addRule("@计算", "addZ ?x 0Z === ?x");
    addRule("@计算", "addZ ?x (pos 0) === succZ ?x");
    addRule("@计算", "addZ ?x (pos (succ ?n)) === succZ (addZ ?x (pos ?n))");
    addRule("@计算", "addZ ?x (neg 0) === predZ ?x");
    addRule("@计算", "addZ ?x (neg (succ ?n)) === predZ (addZ ?x (neg ?n))");
    typeName = "Z.le";
    addRule("定义", "leZ:=Lx:Z,Ly:Z,x=y+Sz:nat,addZ x (pos z) = y");
    typeName = "Z.mul";
    addRule("定义", "mulZ:=λx:Z.ind_Z (λy:Z.Z) 0Z (ind_nat (λy:nat.Z) x (λy:nat.(λh:Z.addZ h x))) (ind_nat (λy:nat.Z) (negZ x) (λy:nat.(λh:Z.addZ h (negZ x))))");
    addRule("@计算", "mulZ ?x 0Z === 0Z");
    addRule("@计算", "mulZ ?x (pos 0) === ?x");
    addRule("@计算", "mulZ ?x (pos (succ ?n)) === addZ (mulZ ?x (pos ?n)) ?x");
    addRule("@计算", "mulZ ?x (neg 0) === negZ ?x");
    addRule("@计算", "mulZ ?x (neg (succ ?n)) === addZ (mulZ ?x (neg ?n)) (negZ ?x)");
    typeName = "Even";
    addRule("类型", "Even:nat->U");
    addRule("构造", "even0:Even 0");
    addRule("构造", "evenss:Px:nat,Even x->Even (succ (succ x))");
    addRule("@解构", "@ind_Even:Pu:U@,PC:Px:nat,Even x->Uu,Pc0:C 0 even0,Pcss:Px:nat,Pe:Even x,C x e->C (succ (succ x)) (evenss x e),Px:nat,Pe:Even x,C x e");
    addRule("@解构", "ind_Even:=@ind_Even _");
    addRule("_解构", "ind_Even");
    addRule("计算", "ind_Even ?C ?c0 ?css 0 even0 === ?c0");
    addRule("计算", "ind_Even ?C ?c0 ?css (succ (succ ?x)) (evenss ?x ?e) === ?css ?x ?e (ind_Even ?C ?c0 ?css ?x ?e)");

    typeName = "Aleph";
    addRule("定义", "Aleph:=ind_nat (λx:nat.U) nat (λx:nat.λx:U.x→Bool)");

    typeName = "List";

    addRule("@类型", "@List:Pu:U@,Uu->Uu");
    addRule("@类型", "List:=@List _");
    addRule("_类型", "List");

    addRule("@构造", "@nil:Pu:U@,Pa:Uu,List a");
    addRule("@构造", "nil:=@nil _ _");
    addRule("_构造", "nil");

    addRule("@构造", "@cons:Pu:U@,Pa:Uu,a->List a->List a");
    addRule("@构造", "cons:=@cons _ _");
    addRule("_构造", "cons");
    addRule("@解构", "@ind_List:Pu:U@,Pv:U@,Pa:Uu,PC:List a->Uv,Pcn:C (@nil u a),Pcc:Px:a,Pxs:List a,C xs->C (@cons u a x xs),Pxs:List a,C xs");
    addRule("@解构", "ind_List:=@ind_List _ _ _");
    addRule("_解构", "ind_List");
    addRule("计算", "ind_List ?C ?cn ?cc nil === ?cn");
    addRule("@计算", "ind_List ?C ?cn ?cc (@nil ?u ?a) === ?cn");
    addRule("计算", "ind_List ?C ?cn ?cc (cons ?x ?xs) === ?cc ?x ?xs (ind_List ?C ?cn ?cc ?xs)");
    addRule("@计算", "ind_List ?C ?cn ?cc (@cons ?u ?a ?x ?xs) === ?cc ?x ?xs (ind_List ?C ?cn ?cc ?xs)");

    typeName = "Option";

    addRule("@类型", "@Option:Pu:U@,Uu->Uu");
    addRule("@类型", "Option:=@Option _");
    addRule("_类型", "Option");
    addRule("@构造", "@none:Pu:U@,Pa:Uu,Option a");
    addRule("@构造", "none:=@none _ _");
    addRule("_构造", "none");
    addRule("@构造", "@some:Pu:U@,Pa:Uu,Px:a,Option a");
    addRule("@构造", "some:=@some _ _");
    addRule("_构造", "some");
    addRule("@解构", "@ind_Option:Pu:U@,Pv:U@,Pa:Uu,PC:@Option u a->Uv,Pcn:C (@none u a),Pcs:Px:a,C (@some u a x),Px:@Option u a,C x");
    addRule("@解构", "ind_Option:=@ind_Option _ _ _");
    addRule("_解构", "ind_Option");
    addRule("计算", "ind_Option ?C ?cn ?cs none === ?cn");
    addRule("@计算", "ind_Option ?C ?cn ?cs (@none ?1 ?2) === ?cn");
    addRule("计算", "ind_Option ?C ?cn ?cs (some ?x) === ?cs ?x");
    addRule("@计算", "ind_Option ?C ?cn ?cs (@some ?1 ?2 ?x) === ?cs ?x");

    typeName = "W";
    addRule("_类型", "Wx:?A,?B x : U_");
    addRule("@构造", "@sup : Pu:U@,Pv:U@,Pa:Uu,Pb:a->Uv,Px:a,Pf:b x->Wx:a,b x,Wx:a,b x");
    addRule("@构造", "sup := @sup _ _ _");
    addRule("_构造", "sup");
    addRule("@解构", "@ind_W : Pu:U@,Pv:U@,Pw:U@,Pa:Uu,Pb:a->Uv,PC:(Wx:a,b x)->Uw,(Px:a,Pf:b x->Wx:a,b x,(Py:b x,C (f y))->C (@sup u v a b x f))->(Pk:Wx:a,b x,C k)");
    addRule("@解构", "ind_W := @ind_W _ _ _ _");
    addRule("_解构", "ind_W");
    addRule("计算", "ind_W ?b ?C ?c (sup ?b ?x ?f) === ?c ?x ?f (Ly:(?b ?x),ind_W ?b ?C ?c (?f y))");
    addRule("@计算", "ind_W _ ?C ?c (sup ?b ?x ?f) === ?c ?x ?f (Ly:(?b ?x),ind_W ?b ?C ?c (?f y))");
    addRule("@计算", "ind_W _ ?C ?c (@sup ?u ?v ?a ?b ?x ?f) === ?c ?x ?f (Ly:(?b ?x),ind_W ?b ?C ?c (?f y))");
    typeName = "W.nat";
    addRule("定义", "NW:=Wx:Bool,ind_Bool (Lx:Bool,U) False True x");
    typeName = "Ord"
    addRule("类型", "Ord:U");
    addRule("构造", "0O:Ord");
    addRule("构造", "succO:Ord->Ord");
    addRule("构造", "limO:(nat->Ord)->Ord");
    addRule("@解构", "@ind_Ord:Pu:U@,PC:Ord->Uu,Pc0:C 0O,Pcs:Po:Ord,(C o)->(C (succO o)),Pclim:Parr:nat->Ord,(Pn:nat,C (arr n))->(C (limO arr)),Px:Ord,C x");
    addRule("@解构", "ind_Ord:=@ind_Ord _");
    addRule("_解构", "ind_Ord");
    addRule("计算", "ind_Ord ?C ?c0 ?cs ?clim 0O === ?c0");
    addRule("@计算", "ind_Ord _ ?c0 _ _ 0O === ?c0");
    addRule("@计算", "@ind_Ord _ _ ?c0 _ _ 0O === ?c0");
    addRule("计算", "ind_Ord ?C ?c0 ?cs ?clim (succO ?o) === ?cs ?o (ind_Ord ?C ?c0 ?cs ?clim ?o)");
    addRule("计算", "ind_Ord ?C ?c0 ?cs ?clim (limO ?f) === ?clim ?f (Ln:nat.ind_Ord ?C ?c0 ?cs ?clim (?f n))");
    // addRule("@计算", "@ind_Ord ?u ?C ?c0 ?cs ?clim (succO ?o) === ?cs ?o (@ind_Ord ?u ?C ?c0 ?cs ?clim ?o)");
    // addRule("@计算", "@ind_Ord ?u ?C ?c0 ?cs ?clim (limO ?f) === ?clim ?f (Ln:nat.@ind_Ord ?u ?C ?c0 ?cs ?clim (?f n))");
    typeName = "(Ord)"
    addRule("定义", "natO:=ind_nat (λx:nat.Ord) 0O λx:nat.λh:Ord.(succO h)");
    addRule("定义", "omega:=limO natO");
    addRule("定义", "leqO:=ind_Ord (Lx:Ord.Ord->U) (Lx:Ord.True) (Lo:Ord.Lleqo:Ord->U.ind_Ord (Lx:Ord.U) False (Lm:Ord.Lleqm:U.leqo m) (Larr:nat->Ord,Lfnleq:Pn:nat,U.Sx:nat,fnleq x)) (Larr:nat->Ord.Lg:nat->Ord->U.Lo:Ord.Px:nat,g x o)");
    addRule("定义", "addO:=ind_Ord (Lx:Ord.Ord->Ord) (Lx:Ord.x) (Lx:Ord.Lf:Ord->Ord,Ly:Ord.succO(f y)) (Larr:nat->Ord.Lg:nat->Ord->Ord.Ly:Ord.limO (Ln:nat.g n y ))");

    typeName = "LiftU";
    addRule("@类型", "@LiftU: Pu:U@.Uu->(U(@succ u))");
    addRule("@类型", "LiftU := @LiftU _");
    addRule("_类型", "LiftU");
    addRule("@构造", "@liftU: Pu:U@.Pa:Uu.a->(LiftU a)");
    addRule("@构造", "liftU:= @liftU _ _");
    addRule("_构造", "liftU");
    addRule("@解构", "@lowerU: Pu:U@.Px:Uu.(LiftU x)-> x");
    addRule("@解构", "lowerU:=@lowerU _ _");
    addRule("_解构", "lowerU");
    addRule("计算", "lowerU (liftU ?x) === ?x");
    addRule("计算", "liftU (lowerU ?x) === ?x");
    addRule("@计算", "lowerU (@liftU ?1 ?2 ?x) === ?x");
    addRule("@计算", "liftU (@lowerU ?1 ?2 ?x) === ?x");
    // addRule("@解构", "@ind_LiftU:=(λu:U@.(λv:U@.(λa:(Uu).(λC:((LiftU a)→(Uv)).(λh:(Πx:a,C (liftU x)).(λx:LiftU a.h (lowerU x))))))):(Πu:U@,(Πv:U@,(Πa:(Uu),(ΠC:((LiftU a)→(Uv)),((Πx:a,C (liftU x))→(Πx:LiftU a,C x))))))");
    // addRule("@解构", "ind_LiftU:=@ind_LiftU _ _ _");
    // addRule("_解构", "ind_LiftU");
    // addRule("_计算", "ind_LiftU ?C ?clift (liftU ?x) === ?clift ?x");

    typeName = "eq.happly";
    addRule("@定义", "@happly:Pu:U@,Pv:U@,Pa:Uu,Pb:a->Uv,Pf:Px:a,b x,Pg:Px:a,b x,(f=g)->(Px:a.(f x)=(g x))");
    // addRule("@定义", "@happly:=(λa:U_.(λb:U_.(λf:(a→b).(λg:(a→b).(λh:f=g.(λx:a.trans (λg:(a→b).(f x)=(g x)) h rfl))))))");
    addRule("@定义", "happly:=@happly _ _ _ _ _ _");
    addRule("_定义", "happly");
    addRule("计算", "happly (refl ?f) ?x === refl (?f ?x)");
    addRule("@计算", "happly rfl _ === rfl");
    addRule("@计算", "happly (@refl ?1 ?2 ?f) ?x === refl (?f ?x)");
    typeName = "fnext";
    // addRule("@构造", "@fnext:Pa:U_.Pb:U_.Pf:a->b.Pg:a->b.(Px:a.(f x)=(g x))->(f=g)");
    addRule("@构造", "@fnext:Pu:U@,Pv:U@,Pa:Uu,Pb:a->Uv,Pf:Px:a,b x,Pg:Px:a,b x,(Px:a,f x=g x)->f=g");
    addRule("@构造", "fnext:=@fnext _ _ _ _ _ _");
    addRule("_构造", "fnext");
    addRule("@计算", "@fnext_happly:Pu:U@,Pv:U@,Pa:Uu,Pb:a->Uv,Pf:Px:a,b x,Pg:Px:a,b x,Px:f=g.(@fnext u v a b f g (@happly u v a b f g x))=x");
    addRule("@计算", "@happly_fnext:Pu:U@,Pv:U@,Pa:Uu,Pb:a->Uv,Pf:Px:a,b x,Pg:Px:a,b x,Px:Px:a.(f x)=(g x).(@happly u v a b f g (@fnext u v a b f g x))=x");
    addRule("@计算", "fnext_happly:=@fnext_happly _ _ _ _ _ _");
    addRule("@计算", "happly_fnext:=@happly_fnext _ _ _ _ _ _");
    addRule("_计算", "fnext_happly");
    addRule("_计算", "happly_fnext");

    typeName = "eqv";
    addRule("_定义", "@eqv:=Lu:U@,La:Uu,Lb:Uu,Sf:a->b,(Sg:b->a,Px:a,x=(g(f x)))X(Sh:b->a,Px:b,x=(f(h x)))");
    addRule("_定义", "eqv:=@eqv _");
    addRule("定义", "?1 ~= ?2 === eqv ?1 ?2");
    typeName = "eqv.refl";
    addRule("@定义", "@eqvrefl:=(λu:U@.(λa:(Uu).(pair (Lf:a->a.(Sg:a->a,Px:a,x=(g(f x)))X(Sh:a->a,Px:a,x=(f(h x)))) (λx:a.x) ((pair (λg:(a→a).(Πx:a,x=(g x))) (λx:a.x) (λx:a.rfl)),(pair (λh:(a→a).(Πx:a,x=(h x))) (λx:a.x) (λx:a.rfl)))))):(Πu:U@,(Πa:(Uu),((a~=a))))");
    addRule("@定义", "eqvrefl:=@eqvrefl _");
    addRule("_定义", "eqvrefl");
    addRule("计算", "pr0 (eqvrefl ?a) === Lx:?a,x");
    typeName = "eqv.id2eqv";
    // addRule("@定义", "@id2eqv:=(λu:U@.(λa:(Uu).(λb:(Uu).(λh:a=b.trans (λx:(Uu).a~=x) h (@eqvrefl u a))))):(Πu:U@,(Πa:(Uu),(Πb:(Uu),((a=b)→(a~=b)))))");
    // addRule("定义", "@id2eqv:=Lu:U@.(λa:Uu.(λb:Uu.(λh':((eq a) b).((((((ind_eq a) (λy':Uu.(λm':((eq a) y').((Σf:(y'→b),((Σg:(b→y'),(Πx:y',((eq x) (g (f x)))))×(Σh:(b→y'),(Πx:b,((eq x) (f (h x)))))))→(Σf:(a→b),((Σg:(b→a),(Πx:a,((eq x) (g (f x)))))×(Σh:(b→a),(Πx:b,((eq x) (f (h x))))))))))) (λm':(Σf:(a→b),((Σg:(b→a),(Πx:a,((eq x) (g (f x)))))×(Σh:(b→a),(Πx:b,((eq x) (f (h x))))))).m')) b) h') (((pair (λf:(b→b).((Σg:(b→b),(Πx:b,((eq x) (g (f x)))))×(Σh:(b→b),(Πx:b,((eq x) (f (h x)))))))) (λx:b.x)) ((((pair (λg:(b→b).(Πx:b,((eq x) (g x))))) (λx:b.x)) (λx:b.rfl)),(((pair (λh:(b→b).(Πx:b,((eq x) (h x))))) (λx:b.x)) (λx:b.rfl)))))))):Pu:U@,(Πa:Uu,(Πb:Uu,(((eq a) b)→((eqv a) b))))");
    addRule("@定义", "@id2eqv:Pu:U@,Pa:Uu,Pb:Uu,a=b->a~=b");
    addRule("@定义", "id2eqv:=@id2eqv _ _ _");
    addRule("定义", "id2eqv");
    addRule("@计算", "id2eqv rfl === eqvrefl _");
    addRule("计算", "id2eqv (refl ?a) === eqvrefl ?a");
    addRule("@计算", "id2eqv (@refl ?u ?A ?a) === eqvrefl ?a");
    typeName = "ua";
    addRule("@构造", "@ua:Pu:U@,Pa:Uu,Pb:Uu,(a~=b)->(a=b)");
    addRule("@构造", "ua:=@ua _ _ _");
    addRule("_构造", "ua");
    addRule("@计算", "@ua_id2eqv: Pu:U@.Pa:Uu.Pb:Uu.Pm:eq a b.(ua (id2eqv m))=m");
    addRule("@计算", "@id2eqv_ua: Pu:U@.Pa:Uu.Pb:Uu.Pm:eqv a b.(id2eqv (ua m))=m");
    addRule("@计算", "ua_id2eqv:=@ua_id2eqv _ _ _");
    addRule("@计算", "id2eqv_ua:=@id2eqv_ua _ _ _");
    addRule("_计算", "ua_id2eqv");
    addRule("_计算", "id2eqv_ua");
    typeName = "naiveqv";
    addRule("_定义", "@naiveqv:=Lu:U@,La:Uu,Lb:Uu,Sf:a->b,Sg:b->a,(Px:a,x=(g(f x)))X(Px:b,x=(f(g x)))");
    addRule("_定义", "naiveqv:=@naiveqv _");


    typeName = "LEM";
    addRule("@构造", "@LEM:Pu:U@,Pa:Uu,[[a]]+ (not[[a]])");
    addRule("@构造", "LEM:=@LEM _");
    addRule("_构造", "LEM");
    typeName = "S1";
    addRule("类型", "S1:U");
    addRule("构造", "base:S1");
    addRule("@构造", "loop:@eq @0 S1 base base");
    addRule("_构造", "loop");
    addRule("@解构", "@ind_S1: Pu:U@,PC:S1->Uu,Pcb:(C base),Pcl: @eq u (C base) (trans C loop cb) cb,Pm:S1,C m");
    addRule("@解构", "ind_S1:=@ind_S1 _");
    addRule("_解构", "ind_S1");
    addRule("计算", "ind_S1 ?C ?cb ?cl base === ?cb");
    addRule("@计算", "@apd_loop : Pu:U@,PC:S1->Uu,Pcb:(C base),Pcl: (trans C loop cb) = cb, apd (ind_S1 C cb cl) loop = cl");
    addRule("@计算", "apd_loop := @apd_loop _ _ _");
    addRule("_计算", "apd_loop");
    typeName = "S1.rec";
    addRule("@解构", "@rec_S1:=Lu:U@.La:Uu.Lcb:a.Lcl:eq cb cb.@ind_S1 u (Lx:S1.a) cb (transconst loop cb*cl)");
    addRule("@解构", "rec_S1:=@rec_S1 _ _");
    addRule("_解构", "rec_S1");
    addRule("计算", "rec_S1 ?cb ?cl base === ?cb");
    typeName = "S1.ap_loop";
    addRule("@计算", "@ap_loop : Pu:U@.Pa:Uu.Pcb:a.Pcl:cb=cb.(ap (rec_S1 cb cl) loop) = cl");
    addRule("@计算", "ap_loop := @ap_loop _ _ _");
    addRule("_计算", "ap_loop");

    typeName = "S1.loop_pow";
    addRule("定义", "loop_pow:=ind_Z (λh:Z.base=base) (refl base) (ind_nat (λh:nat.base=base) loop (λh:nat.compeq loop)) (ind_nat (λh:nat.base=base) (inveq loop) (λh:nat.compeq (inveq loop)))");
    addRule("@计算", "loop_pow 0Z === refl base");
    addRule("@计算", "loop_pow (pos 0) === loop");
    addRule("@计算", "loop_pow (pos (succ ?x)) === loop * loop_pow (pos ?x)");
    addRule("@计算", "loop_pow (neg 0) === inveq loop");
    addRule("@计算", "loop_pow (neg (succ ?x)) === (inveq loop)*loop_pow (neg ?x)");
    typeName = "S1.code";
    addRule("定义", "code_S1:S1->U");
    addRule("计算", "code_S1 base === Z");
    addRule("计算", "code_S1_loop: pr0 (id2eqv (ap code_S1 loop)) = succZ");

    typeName = "S2";
    addRule("类型", "S2:U");
    addRule("构造", "base2:S2");
    addRule("@构造", "surf:@eq @0 (base2 = base2) (refl base2) (refl base2)");
    addRule("_构造", "surf");
    typeName = "eq.trans2"
    addRule("@定义", "@trans2:Pu:U@,Pv:U@,Pa:Uu,Px:a,Py:a,Pm:x=y,Pn:x=y,Pb:a->Uv,m=n->Pu:b x,trans b m u=trans b n u");
    addRule("@定义", "trans2:=@trans2 _ _ _ _ _ _ _");
    addRule("_定义", "trans2");
    addRule("@计算", "trans2 _ rfl _ === rfl");
    addRule("计算", "trans2 ?C (refl ?p) ?x === refl (trans ?C ?p ?x)");
    addRule("@计算", "trans2 ?C (@refl ?1 ?2 ?p) ?x === refl (trans ?C ?p ?x)");
    typeName = "eq.apd2"
    addRule("@定义", "@apd2:Pu:U@,Pv:U@,Pa:Uu,Px:a,Py:a,Pm:x=y,Pn:x=y,Pb:a->Uv,Pf:Px:a,b x,Pr:m=n,(apd f m)=(trans2 b r (f x))*(apd f n)");
    addRule("@定义", "apd2:=@apd2 _ _ _ _ _ _ _ _");
    addRule("_定义", "apd2");
    addRule("@计算", "apd2 _ rfl === rfl");
    addRule("计算", "apd2 ?f (refl ?p) === refl (apd ?f ?p)");
    addRule("@计算", "apd2 ?f (@refl ?1 ?2 ?p) === refl (apd ?f ?p)");

    typeName = "S2.ind";
    addRule("@解构", "@ind_S2: Pu:U@,PC:S2->Uu,Pcb:C base2,Pcs:refl cb=(trans2 C surf cb)*(refl cb),Px:S2,C x");
    addRule("@解构", "ind_S2:=@ind_S2 _");
    addRule("_解构", "ind_S2");
    addRule("计算", "ind_S2 ?C ?cb ?cs base2 === ?cb");
    addRule("@计算", "@apd_surf : Pu:U@,PC:S2->Uu,Pcb:C base2,Pcs:refl cb=(trans2 C surf cb)*(refl cb), apd2 (ind_S2 C cb cs) surf = cs");
    addRule("@计算", "apd_surf := @apd_surf _ _ _");
    addRule("_计算", "apd_surf");
    addRule("@计算", "@apd_surf : Pu:U@,PC:S2->Uu,Pcb:C base2,Pcs:refl cb=(trans2 C surf cb)*(refl cb), apd2 (ind_S2 C cb cs) surf = cs");

    // typeName = "S2.rec";
    // addRule("@解构", "@rec_S2:=Lu:U@.La:Uu.Lcb:a.Lcs:eq (refl cb) (refl cb).@ind_S2 u (Lx:S2.a) cb (transconst loop cb*cl)");
    // addRule("@解构", "rec_S2:=@rec_S2 _ _");
    // addRule("_解构", "rec_S1");
    // addRule("计算", "rec_S1 ?cb ?cl base === ?cb");
    // @compeq_rfl:=(λu:U@.(λa:(Uu).(λx:a.(λy:a.(λm:(x=y).ind_eq x (λy':a.(λm:(x=y').((m▪(refl y'))=m))) rfl y m))))):(Πu:U@,(Πa:(Uu),(Πx:a,(Πy:a,(Πm:(x=y),((m▪(rfl))=m))))))
    // @compeq_re:=(λu:U@.(λa:(Uu).(λx:a.(λy:a.(λz:a.(λp:(y=z).ind_eq y (λz':a.(λp:(y=z').(Πm:(x=y),(Πn:(x=y),(((m▪p)=(n▪p))→(m=n)))))) (λm:(x=y).(λn:(x=y).(λh:((m▪rfl)=(n▪rfl)).(((inveq (@compeq_rfl u a x y m))▪h)▪(@compeq_rfl u a x y n))))) z p)))))):(Πu:U@,(Πa:(Uu),(Πx:a,(Πy:a,(Πz:a,(Πp:(y=z),(Πm:(x=y),(Πn:(x=y),(((m▪p)=(n▪p))→(m=n))))))))))
    // @compeq_le:=(λu:U@.(λa:(Uu).(λx:a.(λy:a.(λz:a.(λp:(x=y).ind_eq x (λy':a.(λp:(x=y').(Πm:(y'=z),(Πn:(y'=z),(((p▪m)=(p▪n))→(m=n)))))) (λm:(x=z).(λn:(x=z).(λh:((rfl▪m)=(rfl▪n)).h))) y p)))))):(Πu:U@,(Πa:(Uu),(Πx:a,(Πy:a,(Πz:a,(Πp:(x=y),(Πm:(y=z),(Πn:(y=z),(((p▪m)=(p▪n))→(m=n))))))))))
    // @ap_loop:=Lu:U@.La:Uu.Lcb:a.Lcl:cb=cb.@compeq_le u a (trans (Lx:S1.a) loop cb) cb cb (transconst loop cb) (ap (rec_S1 a cb cl) loop) cl (inveq (apd_ap (rec_S1 a cb cl) loop)) * (apd_loop (Lx:S1.a) cb cl)

    typeName = "I";
    addRule("类型", "I:U");
    addRule("构造", "0I:I");
    addRule("构造", "1I:I");
    addRule("@构造", "segI:@eq @0 I 0I 1I");
    addRule("_构造", "segI");
    addRule("@解构", "@ind_I: Pu:U@,PC:I->Uu,Pc0:(C 0I),Pc1:(C 1I),(Pcs: @eq u (C 1I) (trans C segI c0) c1,Pm:I,C m)");
    addRule("@解构", "ind_I:=@ind_I _");
    addRule("_解构", "ind_I");
    addRule("计算", "ind_I ?C ?c0 ?c1 ?cs 0I === ?c0");
    // addRule("@计算", "@ind_I _ _ ?c0 _ _ 0I === ?c0");
    addRule("计算", "ind_I ?C ?c0 ?c1 ?cs 1I === ?c1");
    // addRule("@计算", "@ind_I _ _ _ ?c1 _ 1I === ?c1");
    addRule("@计算", "@apd_segI : Pu:U@,PC:I->Uu,Pc0:(C 0I),Pc1:(C 1I),Pcs: @eq u (C 1I) (trans C segI c0) c1,eq (apd (@ind_I u C c0 c1 cs) segI) cs");
    addRule("@计算", "apd_segI := @apd_segI _ _ _ _ _");
    addRule("_计算", "apd_segI : (apd (ind_I ?C ?c0 ?c1 ?cs) segI) = ?cs");

    typeName = "Sus";
    addRule("@类型", "@Sus:Pu:U@. Uu -> Uu");
    addRule("@类型", "Sus:=@Sus _");
    addRule("_类型", "Sus");
    addRule("@构造", "@North:Pu:U@.Pa:Uu.Sus a");
    addRule("@构造", "North:=@North _");
    addRule("_构造", "North");
    addRule("@构造", "@South:Pu:U@.Pa:Uu.Sus a");
    addRule("@构造", "South:=@South _");
    addRule("_构造", "South");
    addRule("@构造", "@merid:Pa:U_.a->(eq (North a) (South a))");
    addRule("@构造", "merid:= @merid _");
    addRule("_构造", "merid");
    addRule("@解构", "@ind_Sus: Pu:U@,Pv:U@,Pa:Uu,PC:Px:Sus a,Uv,Pcn:C (North a),Pcs:C (South a),Pcm:Px:a,trans C (@merid a x) cn = cs, Px:Sus a,C x");
    addRule("@解构", "ind_Sus:=@ind_Sus _ _ _");
    addRule("_解构", "ind_Sus");
    addRule("计算", "ind_Sus ?C ?cn ?cs ?cm (North ?a) === ?cn");
    addRule("计算", "ind_Sus ?C ?cn ?cs ?cm (South ?a) === ?cs");
    addRule("@计算", "ind_Sus ?C ?cn ?cs ?cm (@North ?u ?a) === ?cn");
    addRule("@计算", "ind_Sus ?C ?cn ?cs ?cm (@South ?u ?a) === ?cs");
    addRule("@计算", "@apd_merid : Pu:U@,Pv:U@,Pa:Uu,PC:Px:Sus a,Uv,Pcn:C (North a),Pcs:C (South a),Pcm:Px:a,trans C (@merid a x) cn = cs,Px:a, apd (@ind_Sus u v a C cn cs cm) (@merid a x) = cm x");
    addRule("@计算", "apd_merid := @apd_merid _ _ _ _ _ _ _");
    addRule("_计算", "apd_merid : Px:?a,(apd (ind_Sus ?C ?cn ?cs ?cm) (merid x))=(?cm x)");
    typeName = "Pushout"
    addRule("@类型", "@Pushout:Pu:U@,Pa:Uu,Pb:Uu,Pc:Uu,Pf:c->a,Pg:c->b,Uu");
    addRule("@类型", "Pushout:=@Pushout _ _ _");
    addRule("_类型", "Pushout");
    addRule("@构造", "@pol: Pu:U@,Pa:Uu,Pb:Uu,Pc:Uu,Pf:c->a,Pg:c->b,Px:a,@Pushout u a b c f g");
    addRule("@构造", "pol:= @pol _ _ _");
    addRule("_构造", "pol");
    addRule("@构造", "@por: Pu:U@,Pa:Uu,Pb:Uu,Pc:Uu,Pf:c->a,Pg:c->b,Px:b,@Pushout u a b c f g");
    addRule("@构造", "por:= @por _ _ _");
    addRule("_构造", "por");
    addRule("@构造", "@glue: Pu:U@,Pa:Uu,Pb:Uu,Pc:Uu,Pf:c->a,Pg:c->b,Px:c,pol c f g (f x) = por c f g (g x)");
    addRule("@构造", "glue:=@glue _ _ _");
    addRule("_构造", "glue");
    addRule("@解构", "@ind_Pushout:Pu:U@,Pv:U@,Pa:Uu,Pb:Uu,Pc:Uu,Pf:c->a,Pg:c->b,PC:(@Pushout u a b c f g)->Uv,Pcl:Pxl:a,C (@pol u a b c f g xl),Pcr:Pxr:b,C (@por u a b c f g xr),Pcg:Pxg:c,trans C (@glue u a b c f g xg) (cl (f xg)) = cr (g xg),Pm:@Pushout u a b c f g,C m");
    addRule("@解构", "ind_Pushout:=@ind_Pushout _ _ _ _ _ _ _");
    addRule("_解构", "ind_Pushout");
    addRule("计算", "ind_Pushout ?C ?cl ?cr ?cg (pol ?c ?f ?g ?x) === ?cl ?x");
    addRule("计算", "ind_Pushout ?C ?cl ?cr ?cg (por ?c ?f ?g ?x) === ?cr ?x");
    addRule("@计算", "ind_Pushout ?C ?cl ?cr ?cg (@pol ?u ?a ?b ?c ?f ?g ?x) === ?cl ?x");
    addRule("@计算", "ind_Pushout ?C ?cl ?cr ?cg (@por ?u ?a ?b ?c ?f ?g ?x) === ?cr ?x");

    addRule("@计算", "@apd_glue:Pu:U@,Pv:U@,Pa:Uu,Pb:Uu,Pc:Uu,Pf:c->a,Pg:c->b,PC:(@Pushout u a b c f g)->Uv,Pcl:Pxl:a,C (@pol u a b c f g xl),Pcr:Pxr:b,C (@por u a b c f g xr),Pcg:Pxg:c,trans C (@glue u a b c f g xg) (cl (f xg)) = cr (g xg),Pxg:c,apd (ind_Pushout C cl cr cg) (glue c f g xg) = cg xg");
    addRule("@计算", "apd_glue:=@apd_glue _ _ _ _ _ _ _ _ _ _ _");
    addRule("_计算", "apd_glue");

    typeName = "Pushout.Join";
    addRule("定义", "Join:=La:U_,Lb:U_,Pushout (aXb) pr0 pr1");
    typeName = "Pushout.Wedge";
    addRule("定义", "@Wedge:=La:U_,Lb:U_,Lxa:a,Lxb:b,Pushout True (Lx:True,xa)(Lx:True,xb)");
    addRule("定义", "Wedge:=@Wedge _ _");
    typeName = "S3";
    addRule("类型", "S3:=Sus S2");


    typeName = "Prop";
    addRule("定义", "isProp:=La:U_.Px:a.Py:a.x=y");
    typeName = "Contr";
    addRule("定义", "isContr:=La:U_.Sx:a.Py:a.x=y");
    typeName = "Set";
    addRule("定义", "isSet:=La:U_.Px:a.Py:a.isProp(x=y)");

    typeName = "Trunc";
    addRule("@类型", "@Trunc:Pu:U@. Uu -> Uu");
    addRule("@类型", "@ctorTrunc:Pu:U@.Pa: Uu. a -> (@Trunc u a)");
    addRule("_类型", "[[?a]]:U_");
    addRule("_构造", "[?x]:[[?x：]]");
    addRule("@构造", "@trunc: Pu:U@.Pa:Uu.Px:[[a]].Py:[[a]].x=y");
    addRule("@构造", "trunc:=@trunc _ _");
    addRule("_构造", "trunc");
    addRule("@解构", "@ind_Trunc:Pu:U@,Pv:U@,Pa:Uu,PC:[[a]]->Uv,Pc:Px:a,C[x],(Px:[[a]],Py:[[a]],Pcx:C x,Pcy:C y,trans C (trunc x y) (cx) = cy)->Px:[[a]],C x");
    addRule("@解构", "ind_Trunc:=@ind_Trunc _ _ _");
    addRule("解构", "ind_Trunc");
    addRule("计算", "ind_Trunc ?C ?c ?ctr [?x] === ?c ?x");
    addRule("@计算", "ind_Trunc ?C ?c ?ctr (@ctorTrunc ?u ?a ?x) === ?c ?x");
    addRule("@计算", "@apd_trunc : Pu:U@,Pv:U@,Pa:Uu,PC:[[a]]->Uv,Pc:Px:a,C[x],Pctr:Px:[[a]],Py:[[a]],Pcx:C x,Pcy:C y,trans C (trunc x y) (cx) = cy,Px:[[a]],Py:[[a]],apd (@ind_Trunc u v a C c ctr) (trunc x y) = ctr x y (@ind_Trunc u v a C c ctr x) (@ind_Trunc u v a C c ctr y)");
    addRule("@计算", "apd_trunc := @apd_trunc _ _ _ _ _ _");
    addRule("_计算", "apd_trunc");


    return ruleList;
}